"""
presentation/make_correctness_table.py
---------------------------------------
Run the three Carbon variant-cache correctness checks (the same ones as
model_dev/test_carbon_variant_cache.py) and emit a LaTeX table to
presentation/paper/correctness_table.tex, which main.tex \\input's.

  1. efficient vs brute-force   (must match to fp32 numerics)
  2. identity probe vs full     (cache reproduces the ordinary forward exactly)
  3. real substitutions         (approximation — reported, not asserted)

Needs the Carbon-500M checkpoint (downloaded on first use); CPU fp32 is fine but
slow. GPU recommended.

    python presentation/make_correctness_table.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import torch

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from CARBON_modules import load_carbon_local, load_carbon_variant_cache

OUT = Path(__file__).resolve().parent / "paper" / "correctness_table.tex"


def _cos(a, b):
    a, b = a.reshape(-1).float(), b.reshape(-1).float()
    return torch.nn.functional.cosine_similarity(a, b, dim=0).item()


def main() -> int:
    repo_id = "HuggingFaceBio/Carbon-500M"
    device = "cuda" if torch.cuda.is_available() else "cpu"
    dtype = torch.float32
    print(f"Loading Carbon-500M on {device} ({dtype}) …")
    full_model, tokenizer = load_carbon_local(repo_id, device=device, dtype=dtype)
    vc_eff, _ = load_carbon_variant_cache(repo_id, device=device, dtype=dtype,
                                          backend="efficient")
    vc_bf, _ = load_carbon_variant_cache(repo_id, device=device, dtype=dtype,
                                         backend="bruteforce")

    seq = "<dna>" + "ACGTACGTTTGGCCAA" * 12
    enc = tokenizer(seq, return_tensors="pt", add_special_tokens=False)
    input_ids = enc["input_ids"].to(device)
    ref_len = input_ids.shape[1]
    var_pos = torch.tensor([0, ref_len // 3, 2 * ref_len // 3, ref_len - 1],
                           device=device)

    with torch.no_grad():
        out_eff = vc_eff(input_ids, var_pos)
        out_bf = vc_bf(input_ids, var_pos)
        d1 = (out_eff.last_hidden_state - out_bf.last_hidden_state).abs().max().item()
        c1 = _cos(out_eff.last_hidden_state, out_bf.last_hidden_state)

        full = full_model(input_ids, output_hidden_states=True)
        full_at = full.hidden_states[-1][0].index_select(0, var_pos)
        vc_at = out_eff.last_hidden_state[0]
        d2 = (full_at - vc_at).abs().max().item()
        c2 = _cos(full_at, vc_at)

        dna_lo = 151669
        sub_ids = input_ids[0].index_select(0, var_pos).clone()
        sub_ids = dna_lo + ((sub_ids - dna_lo + 7) % 4096)
        out_sub = vc_eff(input_ids, var_pos, variant_input_ids=sub_ids)
        sub_seq = input_ids.clone(); sub_seq[0, var_pos] = sub_ids
        full_sub = full_model(sub_seq, output_hidden_states=True)
        full_sub_at = full_sub.hidden_states[-1][0].index_select(0, var_pos)
        d3 = (full_sub_at - out_sub.last_hidden_state[0]).abs().max().item()
        c3 = _cos(full_sub_at, out_sub.last_hidden_state[0])

    rows = [
        ("Efficient vs.\\ brute-force", f"${d1:.2e}$", f"${c1:.6f}$"),
        ("Identity probe vs.\\ full forward", f"${d2:.2e}$", f"${c2:.6f}$"),
        ("Real substitutions (approx.)", f"${d3:.2e}$", f"${c3:.6f}$"),
    ]
    body = " \\\\\n    ".join(f"{n} & {d} & {c}" for n, d, c in rows)
    tex = (
        "% Auto-generated by presentation/make_correctness_table.py.\n"
        "\\begin{table}[t]\n  \\centering\n"
        "  \\caption{Variant-cache correctness checks on Carbon-500M (fp32). The "
        "efficient log-sum-exp merge matches the brute-force oracle to numerical "
        "precision, and the identity probe reproduces the ordinary forward; real "
        "substitutions are an approximation, reported (not asserted).}\n"
        "  \\label{tab:correctness}\n"
        "  \\begin{tabular}{lcc}\n    \\toprule\n"
        "    Check & max abs.\\ diff & cosine \\\\\n    \\midrule\n"
        f"    {body} \\\\\n    \\bottomrule\n"
        "  \\end{tabular}\n\\end{table}\n"
    )
    OUT.write_text(tex)
    print(f"Wrote {OUT}")
    print(tex)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
