"""
training/sweeps/soy_carbon_heads.py
-----------------------------------
Fine-tune head models on the soy Carbon-500M window-embedding cache, expressed in
the new sweep infrastructure. Run this *after* the cache exists (generated by
train_pipeline/embed_windows.py into the canonical spec.cache_path location):

    $SVAR_SCRATCH/caches/soy/carbon500m_hw500.ckpt.pt

emb_nn is multi-task (trains all soy traits jointly per run) and consumes the
cache via --cache; each run writes a run_record (features="emb_nn") so results
compare through load_runs() alongside the SNP baselines. GPU-pinned via the
driver's --gpus; resumable (a run whose --output model.pt exists is skipped).

    python -m training.sweep --config training/sweeps/soy_carbon_heads.py --gpus 0 --dry-run
    python -m training.sweep --config training/sweeps/soy_carbon_heads.py --gpus 0
"""
import os
from pathlib import Path

_SCRATCH = os.environ.get("SVAR_SCRATCH", str(Path.home() / "svar_scratch"))
CACHE = f"{_SCRATCH}/caches/soy/carbon500m_hw500.ckpt.pt"

heads = {
    "runner": "emb_nn",
    "name": "carbon500m",
    "gpu": True,
    "fixed": {
        "dataset": "soy",
        "cache": CACHE,
        "half_window": 500,
        "epochs": 30,
        "lr": "1e-3",
        "warm_start_standardizer": True,   # --warm-start-standardizer (bare flag)
        "batch_size": 64,
    },
    "grid": {
        "head": ["linear", "mlp"],
        "pool": ["sum", "mean"],
    },
    "output_template": "trained_heads/soy_carbon500m/{label}/model.pt",
}

SWEEP = [heads]
